---
title: "10: Random and Mixed Effects"
author: "Brian J. Knaus"
date: "11/15/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.align = "center")
```

## 10.1 Linear models


```{r}
library(nlme)
library(MASS) # For the petrol data set.
data(petrol)
library(lattice) # xyplot
```


```{r}
xyplot(Y ~ EP | No, data = petrol,
       xlab = "ASTM end point (deg. F)",
       ylab = "Yield as a percent of crude",
       panel = function(x, y){
         panel.grid()
         m <- sort.list(x)
         panel.xyplot(x[m], y[m], type = "b", cex = 0.5)
       })
```


```{r}
Petrol <- petrol
names(Petrol)
Petrol[,2:5] <- scale(Petrol[,2:5], scale = FALSE)
pet1.lm <- lm(Y ~ No/EP - 1, Petrol)
matrix(round(coef(pet1.lm), 2), 2, 10, byrow = TRUE,
       dimnames = list(c("b0", "b1"), levels(Petrol$No)))
```


```{r}
pet2.lm <- lm(Y ~ No - 1 + EP, Petrol)
anova(pet2.lm, pet1.lm)
```


```{r}
pet3.lm <- lm(Y ~ SG + VP + V10 + EP, Petrol)
anova(pet3.lm, pet2.lm)
```


```{r}
pet3.lme <- lme(Y ~ SG + VP + V10 + EP,
                random = ~ 1 | No, data = Petrol)
summary(pet3.lme)
```


```{r}
pet3.lme <- update(pet3.lme, method = "ML")
summary(pet3.lme)
```


```{r}
anova(pet3.lme, pet3.lm)
```


```{r}
pet4.lme <- update(pet3.lme, fixed = Y ~ V10 + EP)
anova(pet4.lme, pet3.lme)
fixed.effects(pet4.lme)
coef(pet4.lme)
```


```{r}
pet5.lme <- update(pet4.lme, random = ~ 1 + EP | No)
anova(pet4.lme, pet5.lme)
```


### A multi-level study


```{r, eval=FALSE}
library(MASS)
nl1 <- nlschools; attach(nl1)
classMeans <- tapply(IQ, class, mean)
nl1$IQave <- classMeans[as.character(class)]
detach()
cen <- c("IQ", "IQave", "SES")
nl1[cen] <- scale(nl1[cen], center = T, scale = F)
```


```{r, eval=FALSE}
library(nlme)
options(contrasts = c("contr.treatment", "contr.poly"))
nl.lme <- lme(lang ~ IQ*COMB + IQave + SES, random = ~ IQ | class, data = nl1)
summary(nl.lme)
```


```{r}
summary(lm(lang ~ IQ*COMB + SES + class, data = nl1, singular.ok = T), cor = F)
```


```{r}
nl2 <- cbind(aggregate(nl1[c(1, 7)], list(class = nl1$class), mean), 
             unique(nl1[c("class", "COMB", "GS")]))
summary(lm(lang ~ IQave + COMB, data = nl2, weights = GS))
```


### A longitudinal study


```{r}
sitka.lme <- lme(size ~ treat*ordered(Time), random = ~1 | tree,
                 data = Sitka, method = "ML")
Sitka <- Sitka
attach(Sitka)
Sitka$treatslope <- Time * (treat == "ozone")
detach()
sitka.lme2 <- update(sitka.lme, fixed = size ~ ordered(Time) + treat + treatslope)
anova(sitka.lme, sitka.lme2)
matrix(fitted(sitka.lme2, level = 0)[c(301:305, 1:5)], 2, 5, byrow = T,
       dimnames = list(c("control", "ozone"), unique(Sitka$Time)))
```



## 10.2 Classic nested designs


```{r}
library(Rfit)
summary(raov(Conc ~ Lab/Bat, data = coop, subset = Spc=="S1"))



```



## 10.3 Non-linear mixed effects models


## 10.4 Generalized linear mixed models


## 10.5 GEE models





