---
title: "Chapter 14: Time Series Analysis"
author: "Brian Knaus"
date: "December 30, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.align = "center")
knitr::opts_chunk$set(fig.width = 8)
knitr::opts_chunk$set(fig.height = 4)
```


```{r}
lh
```



```{r}
library(MASS)
deaths
tsp(deaths)
start(deaths)
end(deaths)
frequency(deaths)
cycle(deaths)
```

```{r}
par(mfrow = c(1, 2))
ts.plot(lh)
ts.plot(deaths, mdeaths, fdeaths,
        lty = c(1, 3, 4), xlab = "year", ylab = "Deaths")
```


```{r}
aggregate(deaths, nfrequency = 4, FUN = sum)
aggregate(deaths, nfrequency = 1, FUN = mean)
```


## 14.1 Second-Order Summaries


```{r, fig.height=8}
par(mfrow = c(2, 2))
acf(lh)
acf(lh, type = "covariance")
acf(deaths)
acf(ts.union(mdeaths, fdeaths))
```


```{r}
par(mfrow = c(1, 2))
spectrum(lh)
spectrum(deaths)
```


```{r}
par(mfrow = c(2, 2))
spectrum(lh)
spectrum(lh, spans = 3)
spectrum(lh, spans = c(3, 3))
spectrum(lh, spans = c(3, 5))
```


```{r}
spectrum(deaths)
spectrum(deaths, spans = c(3, 3))
spectrum(deaths, spans = c(3, 5))
spectrum(deaths, spans = c(3, 7))
```


```{r}
par(mfrow = c(1, 2))
cpgram(lh)
cpgram(deaths)
```


## 14.2 ARIMA Models


```{r}
ts.sim <- arima.sim(list(order = c(1, 1, 0), ar = 0.7), n = 200)
```

```{r}
par(mfrow = c(1, 2))
acf(lh, type = "partial")
acf(deaths, type = "partial")
```


```{r}
(lh.ar1 <- ar(lh, aic = F, order.max = 1))
cpgram(lh.ar1$resid, main = "AR(1) fit to lh")
(lh.ar <- ar(lh, order.max = 9))
lh.ar$aic
cpgram(lh.ar$resid, main = "AR(3) fit to lh")
```


```{r}
(lh.arima1 <- arima(lh, order = c(1, 0, 0)))
tsdiag(lh.arima1)
(lh.arima3 <- arima(lh, order = c(3, 0, 0)))
tsdiag(lh.arima3)
(lh.arima11 <- arima(lh, order = c(1, 0, 1)))
tsdiag(lh.arima11)
```


```{r}
par(mfrow = c(1, 1))
lh.fore <- predict(lh.arima3, 12)
ts.plot(lh, lh.fore$pred, lh.fore$pred + 2 * lh.fore$se,
        lh.fore$pred - 2 * lh.fore$se)
```


## 14.3 Seasonality


```{r}
deaths.stl <- stl(deaths, "periodic")
dsd <- deaths.stl$rem
ts.plot(deaths, deaths.stl$sea, dsd)
```


```{r}
ts.plot(dsd)
#
acf(dsd, type = "partial")

#ts.plot(dsd); acf(dsd); 

```





## 14.4 Nottingham Temperature Data



## 14.5 Regression with Autocorrelated Errors



## 14.6 Models for Financial Series



